axon:
  eventhandling:
    processors:
      product-group:
        mode: subscribing
server:
  error:
    include-binding-errors: always
    include-message: always
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:~/data/productDB
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: product-service